"""fix_ba_kyc_field

Revision ID: cff3a93792be
Revises: d9ed2dfe78fb
Create Date: 2025-07-28 14:14:35.287881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cff3a93792be'
down_revision: Union[str, None] = 'd9ed2dfe78fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bankaccount', 'kyc_verified_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('bankaccount', 'kyc_verified_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bankaccount', 'kyc_verified_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('bankaccount', 'kyc_verified_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
