"""bank_account_currency_fix

Revision ID: d9ed2dfe78fb
Revises: 20af59520656
Create Date: 2025-07-28 12:14:53.408977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9ed2dfe78fb'
down_revision: Union[str, None] = '20af59520656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankaccount', sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'KES', 'PLN', name='accountcurrencyenum'), nullable=False))
    op.drop_column('bankaccount', 'currency_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankaccount', sa.Column('currency_type', postgresql.ENUM('USD', 'EUR', 'GBP', 'KES', 'PLN', name='accountcurrencyenum'), autoincrement=False, nullable=False))
    op.drop_column('bankaccount', 'currency')
    # ### end Alembic commands ###
